# Superstore Sales Analysis Using SQL

In [ ]:
import sqlite3
from pathlib import Path
import pandas as pd
from IPython.display import display


# STEP 1: LOAD DATASET


base_dir = Path(r"e:\celabal\Superstore_Sales_Analysis_SQL")
csv_path = base_dir / "dataset" / "Superstore.csv"

# Read CSV
raw_df = pd.read_csv(csv_path, encoding="cp1252")

# Standardize column names
raw_df.columns = [
    c.strip()
    .lower()
    .replace(" ", "_")
    .replace("-", "_")
    for c in raw_df.columns
]

# Convert dates
raw_df["order_date"] = pd.to_datetime(
    raw_df["order_date"],
    errors="coerce"
).dt.strftime("%Y-%m-%d")

raw_df["ship_date"] = pd.to_datetime(
    raw_df["ship_date"],
    errors="coerce"
).dt.strftime("%Y-%m-%d")


# STEP 2: CREATE SQLITE DATABASE


conn = sqlite3.connect(":memory:")
conn.execute("PRAGMA foreign_keys = ON;")


# STEP 3: CREATE RAW TABLE


raw_df.to_sql(
    "superstore_raw",
    conn,
    if_exists="replace",
    index=False
)


# STEP 4: CREATE NORMALIZED TABLES


conn.executescript("""

DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;

CREATE TABLE customers (
    customer_id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    segment TEXT,
    country TEXT,
    city TEXT,
    state TEXT,
    postal_code TEXT,
    region TEXT
);

CREATE TABLE products (
    product_id TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT,
    sub_category TEXT
);

CREATE TABLE orders (
    row_id INTEGER PRIMARY KEY,
    order_id TEXT,
    order_date TEXT,
    ship_date TEXT,
    ship_mode TEXT,
    customer_id TEXT,
    product_id TEXT,
    sales REAL,
    quantity INTEGER,
    discount REAL,
    profit REAL,

    FOREIGN KEY(customer_id)
        REFERENCES customers(customer_id),

    FOREIGN KEY(product_id)
        REFERENCES products(product_id)
);

""")


# STEP 5: INSERT DATA


# Customers

raw_df[
    [
        "customer_id",
        "customer_name",
        "segment",
        "country",
        "city",
        "state",
        "postal_code",
        "region"
    ]
].drop_duplicates(
    subset=["customer_id"]
).to_sql(
    "customers",
    conn,
    if_exists="append",
    index=False
)

# Products

raw_df[
    [
        "product_id",
        "product_name",
        "category",
        "sub_category"
    ]
].drop_duplicates(
    subset=["product_id"]
).to_sql(
    "products",
    conn,
    if_exists="append",
    index=False
)

# Orders

raw_df[
    [
        "row_id",
        "order_id",
        "order_date",
        "ship_date",
        "ship_mode",
        "customer_id",
        "product_id",
        "sales",
        "quantity",
        "discount",
        "profit"
    ]
].drop_duplicates(
    subset=["row_id"]
).to_sql(
    "orders",
    conn,
    if_exists="append",
    index=False
)


# STEP 6: DATABASE SUMMARY



print("DATABASE CREATED SUCCESSFULLY")


print(f"\nRows in superstore_raw: {len(raw_df):,}")


# STEP 7: SHOW ALL TABLES


print("\nAVAILABLE TABLES")

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table';
    """,
    conn
)

display(tables)

# STEP 8: SHOW ROW COUNTS


print("\nTABLE ROW COUNTS")

for table in [
    "superstore_raw",
    "customers",
    "products",
    "orders"
]:
    count_df = pd.read_sql_query(
        f"""
        SELECT COUNT(*) AS total_rows
        FROM {table};
        """,
        conn
    )

    print(f"\n{table}")
    display(count_df)


# STEP 9: DISPLAY SAMPLE RECORDS


print("\nCUSTOMERS TABLE")
display(
    pd.read_sql_query(
        "SELECT * FROM customers LIMIT 10;",
        conn
    )
)

print("\nPRODUCTS TABLE")
display(
    pd.read_sql_query(
        "SELECT * FROM products LIMIT 10;",
        conn
    )
)

print("\nORDERS TABLE")
display(
    pd.read_sql_query(
        "SELECT * FROM orders LIMIT 10;",
        conn
    )
)

print("\nSUPERSTORE_RAW TABLE")
display(
    pd.read_sql_query(
        "SELECT * FROM superstore_raw LIMIT 10;",
        conn
    )
)

def run_query(title, sql):
    result = pd.read_sql_query(sql, conn)
    display(result)
    return result

cte_window_results = {}

DATABASE CREATED SUCCESSFULLY

Rows in superstore_raw: 9,994

AVAILABLE TABLES

             name
0  superstore_raw
1       customers
2        products
3          orders

TABLE ROW COUNTS

superstore_raw

   total_rows
0        9994

customers

   total_rows
0         793

products

   total_rows
0        1862

orders

   total_rows
0        9994

CUSTOMERS TABLE

,customer_id,customer_name,segment,country,city,state,postal_code,region
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South
1,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West
2,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South
3,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West
4,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027,South
5,IM-15070,Irene Maddox,Consumer,United States,Seattle,Washington,98103,West
6,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,Central
7,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711,Central
8,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,Utah,84084,West
9,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109,West

PRODUCTS TABLE

,product_id,product_name,category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage
5,FUR-FU-10001487,Eldon Expressions Wood and Plastic Desk Access...,Furniture,Furnishings
6,OFF-AR-10002833,Newell 322,Office Supplies,Art
7,TEC-PH-10002275,Mitel 5320 IP Phone VoIP phone,Technology,Phones
8,OFF-BI-10003910,DXL Angle-View Binders with Locking Rings by S...,Office Supplies,Binders
9,OFF-AP-10002892,Belkin F5C206VTEL 6 Outlet Surge,Office Supplies,Appliances

ORDERS TABLE

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,OFF-ST-10000760,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,FUR-FU-10001487,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,OFF-AR-10002833,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,TEC-PH-10002275,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,OFF-BI-10003910,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,OFF-AP-10002892,114.9000,5,0.00,34.4700

SUPERSTORE_RAW TABLE

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

DATABASE READY FOR ANALYSIS

## Subquery Analysis

These cells answer the first five questions using subqueries.

In [14]:
subquery_results = {}

subqueries = [
    (
        "Q1 - Orders with sales greater than average sales",
        """
        SELECT *
        FROM orders
        WHERE sales > (SELECT AVG(sales) FROM orders)
        ORDER BY sales DESC
        """
    ),
    (
        "Q2 - Highest sales order for every customer",
        """
        SELECT o.*
        FROM orders o
        WHERE o.sales = (
            SELECT MAX(o2.sales)
            FROM orders o2
            WHERE o2.customer_id = o.customer_id
        )
        ORDER BY o.customer_id, o.sales DESC
        """
    ),
    (
        "Q3 - Customers whose sales exceed overall average customer sales",
        """
        WITH customer_totals AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, ct.total_sales
        FROM customer_totals ct
        JOIN customers c ON c.customer_id = ct.customer_id
        WHERE ct.total_sales > (SELECT AVG(total_sales) FROM customer_totals)
        ORDER BY ct.total_sales DESC
        """
    ),
    (
        "Q4 - Products whose sales exceed average product sales",
        """
        WITH product_totals AS (
            SELECT product_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY product_id
        )
        SELECT p.product_id, p.product_name, pt.total_sales
        FROM product_totals pt
        JOIN products p ON p.product_id = pt.product_id
        WHERE pt.total_sales > (SELECT AVG(total_sales) FROM product_totals)
        ORDER BY pt.total_sales DESC
        """
    ),
    (
        "Q5 - Orders with profit greater than average profit",
        """
        SELECT *
        FROM orders
        WHERE profit > (SELECT AVG(profit) FROM orders)
        ORDER BY profit DESC
        """
    ),
]

for label, sql in subqueries:
    subquery_results[label] = run_query(label, sql)

============================================================
Q1 - Orders with sales greater than average sales
============================================================

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit
0,2698,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,TEC-MA-10002412,22638.480,6,0.5,-1811.0784
1,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,TEC-CO-10004722,17499.950,5,0.0,8399.9760
2,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,TEC-CO-10004722,13999.960,4,0.0,6719.9808
3,2624,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,TEC-CO-10004722,11199.968,4,0.2,3919.9888
4,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,TEC-CO-10004722,10499.970,3,0.0,5039.9856
...,...,...,...,...,...,...,...,...,...,...,...
2355,2615,CA-2014-147298,2014-04-26,2014-05-03,Standard Class,AG-10300,FUR-CH-10004886,230.280,3,0.2,23.0280
2356,3752,CA-2017-161956,2017-08-27,2017-08-29,Second Class,DR-12880,FUR-CH-10004886,230.280,3,0.2,23.0280
2357,4553,US-2014-106334,2014-12-27,2015-01-02,Standard Class,JF-15490,FUR-CH-10004886,230.280,3,0.2,23.0280
2358,7932,US-2016-168095,2016-07-15,2016-07-20,Standard Class,MC-17425,FUR-CH-10004886,230.280,3,0.2,23.0280
2359,6389,CA-2014-134103,2014-01-30,2014-02-04,Standard Class,MV-18190,OFF-ST-10000991,229.940,2,0.0,6.8982

============================================================
Q2 - Highest sales order for every customer
============================================================

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit
0,5199,CA-2016-103982,2016-03-03,2016-03-08,Standard Class,AA-10315,OFF-SU-10000151,3930.072,3,0.2,-786.0144
1,2264,CA-2016-131065,2016-11-14,2016-11-16,Second Class,AA-10375,TEC-AC-10004145,499.980,2,0.0,114.9954
2,7706,CA-2016-114601,2016-08-26,2016-09-02,Standard Class,AA-10480,TEC-AC-10003911,479.970,3,0.0,163.1898
3,8010,CA-2015-110863,2015-11-17,2015-11-24,Standard Class,AA-10645,FUR-CH-10002073,1323.900,5,0.0,383.9310
4,8803,CA-2016-140935,2016-11-10,2016-11-12,First Class,AB-10015,FUR-BO-10003966,341.960,2,0.0,54.7136
...,...,...,...,...,...,...,...,...,...,...,...
790,9042,CA-2014-114335,2014-09-28,2014-10-03,Standard Class,XP-21865,FUR-FU-10000277,337.088,4,0.2,16.8544
791,3071,CA-2014-119375,2014-11-17,2014-11-22,Standard Class,YC-21895,OFF-ST-10002011,2934.330,7,0.0,792.2691
792,6210,CA-2017-119809,2017-08-18,2017-08-25,Standard Class,YS-21880,OFF-BI-10003925,2793.528,9,0.2,942.8157
793,5189,CA-2015-115567,2015-09-13,2015-09-18,Standard Class,ZC-21910,FUR-CH-10000015,1516.200,7,0.0,394.2120
794,3815,CA-2016-152471,2016-07-08,2016-07-08,Same Day,ZD-21925,TEC-PH-10002824,823.960,5,0.2,51.4975

============================================================
Q3 - Customers whose sales exceed overall average customer sales
============================================================

    customer_id  customer_name  total_sales
0      SM-20320    Sean Miller    25043.050
1      TC-20980   Tamara Chand    19052.218
2      RB-19360   Raymond Buch    15117.339
3      TA-21385   Tom Ashbrook    14595.620
4      AB-10105  Adrian Barton    14473.571
..          ...            ...          ...
289    JK-16120     Julie Kriz     2932.484
290    SW-20455    Shaun Weien     2921.544
291    ML-17410   Maris LaWare     2921.500
292    RD-19585       Rob Dowd     2912.894
293    CY-12745   Craig Yedwab     2900.026

[294 rows x 3 columns]

============================================================
Q4 - Products whose sales exceed average product sales
============================================================

,product_id,product_name,total_sales
0,TEC-CO-10004722,Canon imageCLASS 2200 Advanced Copier,61599.824
1,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384
2,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,22638.480
3,FUR-CH-10002024,HON 5400 Series Task Chairs for Big and Tall,21870.576
4,OFF-BI-10001359,GBC DocuBind TL300 Electric Binding System,19823.479
...,...,...,...
442,TEC-PH-10001809,Panasonic KX T7736-B Digital phone,1259.580
443,TEC-AC-10001539,Logitech G430 Surround Sound Gaming Headset wi...,1247.844
444,OFF-AP-10000026,Tripp Lite Isotel 6 Outlet Surge Protector wit...,1243.788
445,FUR-CH-10003846,Hon Valutask Swivel Chairs,1242.054
446,OFF-ST-10001837,"SAFCO Mobile Desk Side File, Wire Frame",1240.040

============================================================
Q5 - Orders with profit greater than average profit
============================================================

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit
0,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,TEC-CO-10004722,17499.950,5,0.0,8399.9760
1,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,TEC-CO-10004722,13999.960,4,0.0,6719.9808
2,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,TEC-CO-10004722,10499.970,3,0.0,5039.9856
3,9040,CA-2016-117121,2016-12-17,2016-12-21,Standard Class,AB-10105,OFF-BI-10000545,9892.740,13,0.0,4946.3700
4,4099,CA-2014-116904,2014-09-23,2014-09-28,Standard Class,SC-20095,OFF-BI-10001120,9449.950,5,0.0,4630.4755
...,...,...,...,...,...,...,...,...,...,...,...
2546,4792,CA-2015-104346,2015-12-11,2015-12-16,Standard Class,IM-15070,OFF-PA-10001166,85.056,3,0.2,28.7064
2547,5370,CA-2017-147403,2017-09-10,2017-09-13,First Class,KH-16630,OFF-PA-10003302,85.056,3,0.2,28.7064
2548,9881,CA-2015-104297,2015-05-29,2015-05-31,First Class,CC-12100,OFF-PA-10000474,85.056,3,0.2,28.7064
2549,6198,CA-2015-149909,2015-11-13,2015-11-17,Standard Class,RA-19915,OFF-PA-10000726,63.770,7,0.0,28.6965
2550,5120,CA-2015-127173,2015-09-26,2015-10-03,Standard Class,GM-14500,OFF-BI-10000088,79.056,9,0.2,28.6578

## CTE and Window Function Analysis

These cells answer questions 6 through 20 using CTEs and window functions.

In [15]:
cte_window_results = {}

cte_window_queries = [
    (
        "Q6 - Total sales per customer",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cs.total_sales
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        ORDER BY cs.total_sales DESC
        """
    ),
    (
        "Q7 - Total profit per customer",
        """
        WITH customer_profit AS (
            SELECT customer_id, SUM(profit) AS total_profit
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cp.total_profit
        FROM customer_profit cp
        JOIN customers c ON c.customer_id = cp.customer_id
        ORDER BY cp.total_profit DESC
        """
    ),
    (
        "Q8 - Total quantity purchased by each customer",
        """
        WITH customer_quantity AS (
            SELECT customer_id, SUM(quantity) AS total_quantity
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cq.total_quantity
        FROM customer_quantity cq
        JOIN customers c ON c.customer_id = cq.customer_id
        ORDER BY cq.total_quantity DESC
        """
    ),
    (
        "Q9 - Customers whose sales are above average customer sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cs.total_sales
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        WHERE cs.total_sales > (SELECT AVG(total_sales) FROM customer_sales)
        ORDER BY cs.total_sales DESC
        """
    ),
    (
        "Q10 - Customers generating more than 10000 sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cs.total_sales
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        WHERE cs.total_sales > 10000
        ORDER BY cs.total_sales DESC
        """
    ),
    (
        "Q11 - Rank customers based on total sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cs.total_sales,
               RANK() OVER (ORDER BY cs.total_sales DESC) AS sales_rank
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        ORDER BY sales_rank, c.customer_name
        """
    ),
    (
        "Q12 - Row numbers for each order within customers",
        """
        SELECT o.*,
               ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date, row_id) AS order_number_within_customer
        FROM orders o
        ORDER BY customer_id, order_date, row_id
        """
    ),
    (
        "Q13 - Top 3 customers",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        ), ranked_customers AS (
            SELECT customer_id, total_sales,
                   RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
            FROM customer_sales
        )
        SELECT c.customer_id, c.customer_name, rc.total_sales, rc.sales_rank
        FROM ranked_customers rc
        JOIN customers c ON c.customer_id = rc.customer_id
        WHERE rc.sales_rank <= 3
        ORDER BY rc.sales_rank, c.customer_name
        """
    ),
    (
        "Q14 - Top 10 customers",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        ), ranked_customers AS (
            SELECT customer_id, total_sales,
                   RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
            FROM customer_sales
        )
        SELECT c.customer_id, c.customer_name, rc.total_sales, rc.sales_rank
        FROM ranked_customers rc
        JOIN customers c ON c.customer_id = rc.customer_id
        WHERE rc.sales_rank <= 10
        ORDER BY rc.sales_rank, c.customer_name
        """
    ),
    (
        "Q15 - Highest sale order per customer using ROW_NUMBER()",
        """
        WITH ranked_orders AS (
            SELECT o.*,
                   ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY sales DESC, order_date DESC, row_id DESC) AS rn
            FROM orders o
        )
        SELECT *
        FROM ranked_orders
        WHERE rn = 1
        ORDER BY customer_id
        """
    ),
    (
        "Q16 - Cumulative sales",
        """
        SELECT o.order_date, o.row_id, o.order_id, o.sales,
               SUM(sales) OVER (ORDER BY order_date, row_id) AS cumulative_sales
        FROM orders o
        ORDER BY order_date, row_id
        """
    ),
    (
        "Q17 - Running profit",
        """
        SELECT o.order_date, o.row_id, o.order_id, o.profit,
               SUM(profit) OVER (ORDER BY order_date, row_id) AS running_profit
        FROM orders o
        ORDER BY order_date, row_id
        """
    ),
    (
        "Q18 - Dense rank based on customer sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_id, c.customer_name, cs.total_sales,
               DENSE_RANK() OVER (ORDER BY cs.total_sales DESC) AS sales_dense_rank
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        ORDER BY sales_dense_rank, c.customer_name
        """
    ),
    (
        "Q19 - Second highest customer sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        ), ranked AS (
            SELECT customer_id, total_sales,
                   DENSE_RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
            FROM customer_sales
        )
        SELECT c.customer_id, c.customer_name, r.total_sales
        FROM ranked r
        JOIN customers c ON c.customer_id = r.customer_id
        WHERE r.sales_rank = 2
        ORDER BY c.customer_name
        """
    ),
    (
        "Q20 - Third highest customer sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        ), ranked AS (
            SELECT customer_id, total_sales,
                   DENSE_RANK() OVER (ORDER BY total_sales DESC) AS sales_rank
            FROM customer_sales
        )
        SELECT c.customer_id, c.customer_name, r.total_sales
        FROM ranked r
        JOIN customers c ON c.customer_id = r.customer_id
        WHERE r.sales_rank = 3
        ORDER BY c.customer_name
        """
    ),
]

for label, sql in cte_window_queries:
    cte_window_results[label] = run_query(label, sql)

============================================================
Q6 - Total sales per customer
============================================================

    customer_id    customer_name  total_sales
0      SM-20320      Sean Miller    25043.050
1      TC-20980     Tamara Chand    19052.218
2      RB-19360     Raymond Buch    15117.339
3      TA-21385     Tom Ashbrook    14595.620
4      AB-10105    Adrian Barton    14473.571
..          ...              ...          ...
788    RS-19870       Roy Skaria       22.328
789    MG-18205  Mitch Gastineau       16.739
790    CJ-11875     Carl Jackson       16.520
791    LD-16855     Lela Donovan        5.304
792    TS-21085    Thais Sissman        4.833

[793 rows x 3 columns]

============================================================
Q7 - Total profit per customer
============================================================

    customer_id   customer_name  total_profit
0      TC-20980    Tamara Chand     8981.3239
1      RB-19360    Raymond Buch     6976.0959
2      SC-20095    Sanjit Chand     5757.4119
3      HL-15040    Hunter Lopez     5622.4292
4      AB-10105   Adrian Barton     5444.8055
..          ...             ...           ...
788    HG-14965   Henry Goldwyn    -2797.9635
789    SR-20425  Sharelle Roach    -3333.9144
790    LF-17185     Luke Foster    -3583.9770
791    GT-14635  Grant Thornton    -4108.6589
792    CS-12505   Cindy Stewart    -6626.3895

[793 rows x 3 columns]

============================================================
Q8 - Total quantity purchased by each customer
============================================================

    customer_id      customer_name  total_quantity
0      JD-15895   Jonathan Doherty             150
1      WB-21850      William Brown             146
2      JL-15835           John Lee             143
3      PP-18955         Paul Prost             138
4      SC-20725  Steven Cartwright             133
..          ...                ...             ...
788    RM-19750      Roland Murray               4
789    TS-21085      Thais Sissman               4
790    JR-15700     Jocasta Rupert               3
791    LD-16855       Lela Donovan               3
792    AO-10810  Anthony O'Donnell               2

[793 rows x 3 columns]

============================================================
Q9 - Customers whose sales are above average customer sales
============================================================

    customer_id  customer_name  total_sales
0      SM-20320    Sean Miller    25043.050
1      TC-20980   Tamara Chand    19052.218
2      RB-19360   Raymond Buch    15117.339
3      TA-21385   Tom Ashbrook    14595.620
4      AB-10105  Adrian Barton    14473.571
..          ...            ...          ...
289    JK-16120     Julie Kriz     2932.484
290    SW-20455    Shaun Weien     2921.544
291    ML-17410   Maris LaWare     2921.500
292    RD-19585       Rob Dowd     2912.894
293    CY-12745   Craig Yedwab     2900.026

[294 rows x 3 columns]

============================================================
Q10 - Customers generating more than 10000 sales
============================================================

   customer_id       customer_name  total_sales
0     SM-20320         Sean Miller    25043.050
1     TC-20980        Tamara Chand    19052.218
2     RB-19360        Raymond Buch    15117.339
3     TA-21385        Tom Ashbrook    14595.620
4     AB-10105       Adrian Barton    14473.571
5     KL-16645        Ken Lonsdale    14175.229
6     SC-20095        Sanjit Chand    14142.334
7     HL-15040        Hunter Lopez    12873.298
8     SE-20110        Sanjit Engle    12209.438
9     CC-12370  Christopher Conant    12129.072
10    TS-21370        Todd Sumrall    11891.751
11    GT-14710           Greg Tran    11820.120
12    BM-11140        Becky Martin    11789.630
13    SV-20365         Seth Vernon    11470.950
14    CJ-12010     Caroline Jumper    11164.974
15    CL-12565         Clay Ludtke    10880.546
16    ME-17320       Maria Etezadi    10663.728
17    KF-16285      Karen Ferguson    10604.266
18    BS-11365        Bill Shonely    10501.653
19    EH-13765        Edward Hooks    10310.880

============================================================
Q11 - Rank customers based on total sales
============================================================

    customer_id    customer_name  total_sales  sales_rank
0      SM-20320      Sean Miller    25043.050           1
1      TC-20980     Tamara Chand    19052.218           2
2      RB-19360     Raymond Buch    15117.339           3
3      TA-21385     Tom Ashbrook    14595.620           4
4      AB-10105    Adrian Barton    14473.571           5
..          ...              ...          ...         ...
788    RS-19870       Roy Skaria       22.328         789
789    MG-18205  Mitch Gastineau       16.739         790
790    CJ-11875     Carl Jackson       16.520         791
791    LD-16855     Lela Donovan        5.304         792
792    TS-21085    Thais Sissman        4.833         793

[793 rows x 4 columns]

============================================================
Q12 - Row numbers for each order within customers
============================================================

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,order_number_within_customer
0,2230,CA-2014-128055,2014-03-31,2014-04-05,Standard Class,AA-10315,OFF-BI-10004390,673.568,2,0.2,252.5880,1
1,2231,CA-2014-128055,2014-03-31,2014-04-05,Standard Class,AA-10315,OFF-AP-10002765,52.980,2,0.0,14.8344,2
2,7469,CA-2014-138100,2014-09-15,2014-09-20,Standard Class,AA-10315,OFF-PA-10000349,14.940,3,0.0,7.0218,3
3,7470,CA-2014-138100,2014-09-15,2014-09-20,Standard Class,AA-10315,FUR-FU-10002456,14.560,2,0.0,6.2608,4
4,1300,CA-2015-121391,2015-10-04,2015-10-07,First Class,AA-10315,OFF-ST-10001590,26.960,2,0.0,7.0096,5
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,5899,CA-2016-167682,2016-04-03,2016-04-09,Standard Class,ZD-21925,TEC-PH-10000673,259.960,4,0.0,124.7808,5
9990,3041,US-2016-147991,2016-05-05,2016-05-09,Standard Class,ZD-21925,FUR-FU-10004270,16.720,5,0.2,3.3440,6
9991,3815,CA-2016-152471,2016-07-08,2016-07-08,Same Day,ZD-21925,TEC-PH-10002824,823.960,5,0.2,51.4975,7
9992,3816,CA-2016-152471,2016-07-08,2016-07-08,Same Day,ZD-21925,OFF-PA-10004965,15.984,2,0.2,4.9950,8
9993,8342,CA-2017-141481,2017-06-11,2017-06-14,First Class,ZD-21925,OFF-AP-10004532,61.440,3,0.0,16.5888,9

============================================================
Q13 - Top 3 customers
============================================================

  customer_id customer_name  total_sales  sales_rank
0    SM-20320   Sean Miller    25043.050           1
1    TC-20980  Tamara Chand    19052.218           2
2    RB-19360  Raymond Buch    15117.339           3

============================================================
Q14 - Top 10 customers
============================================================

  customer_id       customer_name  total_sales  sales_rank
0    SM-20320         Sean Miller    25043.050           1
1    TC-20980        Tamara Chand    19052.218           2
2    RB-19360        Raymond Buch    15117.339           3
3    TA-21385        Tom Ashbrook    14595.620           4
4    AB-10105       Adrian Barton    14473.571           5
5    KL-16645        Ken Lonsdale    14175.229           6
6    SC-20095        Sanjit Chand    14142.334           7
7    HL-15040        Hunter Lopez    12873.298           8
8    SE-20110        Sanjit Engle    12209.438           9
9    CC-12370  Christopher Conant    12129.072          10

============================================================
Q15 - Highest sale order per customer using ROW_NUMBER()
============================================================

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,rn
0,5199,CA-2016-103982,2016-03-03,2016-03-08,Standard Class,AA-10315,OFF-SU-10000151,3930.072,3,0.2,-786.0144,1
1,2264,CA-2016-131065,2016-11-14,2016-11-16,Second Class,AA-10375,TEC-AC-10004145,499.980,2,0.0,114.9954,1
2,7706,CA-2016-114601,2016-08-26,2016-09-02,Standard Class,AA-10480,TEC-AC-10003911,479.970,3,0.0,163.1898,1
3,8010,CA-2015-110863,2015-11-17,2015-11-24,Standard Class,AA-10645,FUR-CH-10002073,1323.900,5,0.0,383.9310,1
4,8803,CA-2016-140935,2016-11-10,2016-11-12,First Class,AB-10015,FUR-BO-10003966,341.960,2,0.0,54.7136,1
...,...,...,...,...,...,...,...,...,...,...,...,...
788,9042,CA-2014-114335,2014-09-28,2014-10-03,Standard Class,XP-21865,FUR-FU-10000277,337.088,4,0.2,16.8544,1
789,3071,CA-2014-119375,2014-11-17,2014-11-22,Standard Class,YC-21895,OFF-ST-10002011,2934.330,7,0.0,792.2691,1
790,6210,CA-2017-119809,2017-08-18,2017-08-25,Standard Class,YS-21880,OFF-BI-10003925,2793.528,9,0.2,942.8157,1
791,5189,CA-2015-115567,2015-09-13,2015-09-18,Standard Class,ZC-21910,FUR-CH-10000015,1516.200,7,0.0,394.2120,1
792,3815,CA-2016-152471,2016-07-08,2016-07-08,Same Day,ZD-21925,TEC-PH-10002824,823.960,5,0.2,51.4975,1

============================================================
Q16 - Cumulative sales
============================================================

      order_date  row_id        order_id    sales  cumulative_sales
0     2014-01-03    7981  CA-2014-103800   16.448      1.644800e+01
1     2014-01-04     740  CA-2014-112326   11.784      2.823200e+01
2     2014-01-04     741  CA-2014-112326  272.736      3.009680e+02
3     2014-01-04     742  CA-2014-112326    3.540      3.045080e+02
4     2014-01-05    1760  CA-2014-141817   19.536      3.240440e+02
...          ...     ...             ...      ...               ...
9989  2017-12-30     908  CA-2017-143259   90.930      2.297110e+06
9990  2017-12-30     909  CA-2017-143259   52.776      2.297163e+06
9991  2017-12-30    1297  CA-2017-115427   13.904      2.297177e+06
9992  2017-12-30    1298  CA-2017-115427   20.720      2.297198e+06
9993  2017-12-30    5092  CA-2017-156720    3.024      2.297201e+06

[9994 rows x 5 columns]

============================================================
Q17 - Running profit
============================================================

      order_date  row_id        order_id   profit  running_profit
0     2014-01-03    7981  CA-2014-103800   5.5512          5.5512
1     2014-01-04     740  CA-2014-112326   4.2717          9.8229
2     2014-01-04     741  CA-2014-112326 -64.7748        -54.9519
3     2014-01-04     742  CA-2014-112326  -5.4870        -60.4389
4     2014-01-05    1760  CA-2014-141817   4.8840        -55.5549
...          ...     ...             ...      ...             ...
9989  2017-12-30     908  CA-2017-143259   2.7279     286366.8417
9990  2017-12-30     909  CA-2017-143259  19.7910     286386.6327
9991  2017-12-30    1297  CA-2017-115427   4.5188     286391.1515
9992  2017-12-30    1298  CA-2017-115427   6.4750     286397.6265
9993  2017-12-30    5092  CA-2017-156720  -0.6048     286397.0217

[9994 rows x 5 columns]

============================================================
Q18 - Dense rank based on customer sales
============================================================

    customer_id    customer_name  total_sales  sales_dense_rank
0      SM-20320      Sean Miller    25043.050                 1
1      TC-20980     Tamara Chand    19052.218                 2
2      RB-19360     Raymond Buch    15117.339                 3
3      TA-21385     Tom Ashbrook    14595.620                 4
4      AB-10105    Adrian Barton    14473.571                 5
..          ...              ...          ...               ...
788    RS-19870       Roy Skaria       22.328               789
789    MG-18205  Mitch Gastineau       16.739               790
790    CJ-11875     Carl Jackson       16.520               791
791    LD-16855     Lela Donovan        5.304               792
792    TS-21085    Thais Sissman        4.833               793

[793 rows x 4 columns]

============================================================
Q19 - Second highest customer sales
============================================================

  customer_id customer_name  total_sales
0    TC-20980  Tamara Chand    19052.218

============================================================
Q20 - Third highest customer sales
============================================================

  customer_id customer_name  total_sales
0    RB-19360  Raymond Buch    15117.339

## Business, Profit, and Advanced Analysis

These cells answer questions 21 through 70 and include the final ranked customer report.

In [16]:
business_results = {}

customer_analysis = [
    (
        "Q21 - Top 5 customers",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_name, cs.total_sales
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        ORDER BY cs.total_sales DESC
        LIMIT 5
        """
    ),
    (
        "Q22 - Bottom 5 customers",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_name, cs.total_sales
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        ORDER BY cs.total_sales ASC
        LIMIT 5
        """
    ),
    (
        "Q23 - Customers who placed only one order",
        """
        SELECT c.customer_id, c.customer_name, COUNT(DISTINCT o.order_id) AS order_count
        FROM customers c
        JOIN orders o ON o.customer_id = c.customer_id
        GROUP BY c.customer_id, c.customer_name
        HAVING COUNT(DISTINCT o.order_id) = 1
        ORDER BY c.customer_name
        """
    ),
    (
        "Q24 - Customers who placed more than 10 orders",
        """
        SELECT c.customer_id, c.customer_name, COUNT(DISTINCT o.order_id) AS order_count
        FROM customers c
        JOIN orders o ON o.customer_id = c.customer_id
        GROUP BY c.customer_id, c.customer_name
        HAVING COUNT(DISTINCT o.order_id) > 10
        ORDER BY order_count DESC, c.customer_name
        """
    ),
    (
        "Q25 - Customers with above-average sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_name, cs.total_sales
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        WHERE cs.total_sales > (SELECT AVG(total_sales) FROM customer_sales)
        ORDER BY cs.total_sales DESC
        """
    ),
    (
        "Q26 - Customers generated highest profit",
        """
        WITH customer_profit AS (
            SELECT customer_id, SUM(profit) AS total_profit
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_name, cp.total_profit
        FROM customer_profit cp
        JOIN customers c ON c.customer_id = cp.customer_id
        ORDER BY cp.total_profit DESC
        LIMIT 1
        """
    ),
    (
        "Q27 - Customer purchased maximum quantity",
        """
        WITH customer_qty AS (
            SELECT customer_id, SUM(quantity) AS total_quantity
            FROM orders
            GROUP BY customer_id
        )
        SELECT c.customer_name, cq.total_quantity
        FROM customer_qty cq
        JOIN customers c ON c.customer_id = cq.customer_id
        ORDER BY cq.total_quantity DESC
        LIMIT 1
        """
    ),
    (
        "Q28 - Customer with highest order value",
        """
        SELECT c.customer_name, o.order_id, o.sales
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        ORDER BY o.sales DESC, o.order_date DESC
        LIMIT 1
        """
    ),
    (
        "Q29 - Customer with lowest order value",
        """
        SELECT c.customer_name, o.order_id, o.sales
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        ORDER BY o.sales ASC, o.order_date ASC
        LIMIT 1
        """
    ),
    (
        "Q30 - Customers who never generated profit",
        """
        SELECT c.customer_id, c.customer_name, SUM(o.profit) AS total_profit
        FROM customers c
        JOIN orders o ON o.customer_id = c.customer_id
        GROUP BY c.customer_id, c.customer_name
        HAVING SUM(o.profit) <= 0
        ORDER BY total_profit ASC, c.customer_name
        """
    ),
]

product_analysis = [
    (
        "Q31 - Top 5 products by sales",
        """
        SELECT p.product_id, p.product_name, SUM(o.sales) AS total_sales
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.product_id, p.product_name
        ORDER BY total_sales DESC
        LIMIT 5
        """
    ),
    (
        "Q32 - Bottom 5 products by sales",
        """
        SELECT p.product_id, p.product_name, SUM(o.sales) AS total_sales
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.product_id, p.product_name
        ORDER BY total_sales ASC
        LIMIT 5
        """
    ),
    (
        "Q33 - Top 5 products by profit",
        """
        SELECT p.product_id, p.product_name, SUM(o.profit) AS total_profit
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.product_id, p.product_name
        ORDER BY total_profit DESC
        LIMIT 5
        """
    ),
    (
        "Q34 - Most sold product",
        """
        SELECT p.product_id, p.product_name, SUM(o.quantity) AS total_quantity
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.product_id, p.product_name
        ORDER BY total_quantity DESC
        LIMIT 1
        """
    ),
    (
        "Q35 - Least sold product",
        """
        SELECT p.product_id, p.product_name, SUM(o.quantity) AS total_quantity
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.product_id, p.product_name
        ORDER BY total_quantity ASC
        LIMIT 1
        """
    ),
    (
        "Q36 - Highest revenue generating category",
        """
        SELECT p.category, SUM(o.sales) AS total_sales
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.category
        ORDER BY total_sales DESC
        LIMIT 1
        """
    ),
    (
        "Q37 - Lowest revenue generating category",
        """
        SELECT p.category, SUM(o.sales) AS total_sales
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.category
        ORDER BY total_sales ASC
        LIMIT 1
        """
    ),
    (
        "Q38 - Highest profit generating sub-category",
        """
        SELECT p.sub_category, SUM(o.profit) AS total_profit
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.sub_category
        ORDER BY total_profit DESC
        LIMIT 1
        """
    ),
    (
        "Q39 - Lowest profit generating sub-category",
        """
        SELECT p.sub_category, SUM(o.profit) AS total_profit
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.sub_category
        ORDER BY total_profit ASC
        LIMIT 1
        """
    ),
    (
        "Q40 - Products with above-average sales",
        """
        WITH product_sales AS (
            SELECT product_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY product_id
        )
        SELECT p.product_id, p.product_name, ps.total_sales
        FROM product_sales ps
        JOIN products p ON p.product_id = ps.product_id
        WHERE ps.total_sales > (SELECT AVG(total_sales) FROM product_sales)
        ORDER BY ps.total_sales DESC
        """
    ),
]

regional_analysis = [
    (
        "Q41 - Top performing region",
        """
        SELECT c.region, SUM(o.sales) AS total_sales
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.region
        ORDER BY total_sales DESC
        LIMIT 1
        """
    ),
    (
        "Q42 - Lowest performing region",
        """
        SELECT c.region, SUM(o.sales) AS total_sales
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.region
        ORDER BY total_sales ASC
        LIMIT 1
        """
    ),
    (
        "Q43 - Region with highest profit",
        """
        SELECT c.region, SUM(o.profit) AS total_profit
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.region
        ORDER BY total_profit DESC
        LIMIT 1
        """
    ),
    (
        "Q44 - Region with highest quantity sold",
        """
        SELECT c.region, SUM(o.quantity) AS total_quantity
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.region
        ORDER BY total_quantity DESC
        LIMIT 1
        """
    ),
    (
        "Q45 - State with highest sales",
        """
        SELECT c.state, SUM(o.sales) AS total_sales
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.state
        ORDER BY total_sales DESC
        LIMIT 1
        """
    ),
    (
        "Q46 - State with highest profit",
        """
        SELECT c.state, SUM(o.profit) AS total_profit
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.state
        ORDER BY total_profit DESC
        LIMIT 1
        """
    ),
    (
        "Q47 - Top 10 cities by sales",
        """
        SELECT c.city, SUM(o.sales) AS total_sales
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.city
        ORDER BY total_sales DESC
        LIMIT 10
        """
    ),
    (
        "Q48 - Top 10 cities by profit",
        """
        SELECT c.city, SUM(o.profit) AS total_profit
        FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
        GROUP BY c.city
        ORDER BY total_profit DESC
        LIMIT 10
        """
    ),
]

profit_analysis = [
    ("Q49 - Total company profit", "SELECT SUM(profit) AS total_company_profit FROM orders"),
    ("Q50 - Average profit per order", "SELECT AVG(profit) AS average_profit_per_order FROM orders"),
    (
        "Q51 - Most profitable order",
        "SELECT order_id, row_id, sales, profit FROM orders ORDER BY profit DESC, sales DESC LIMIT 1"
    ),
    (
        "Q52 - Least profitable order",
        "SELECT order_id, row_id, sales, profit FROM orders ORDER BY profit ASC, sales ASC LIMIT 1"
    ),
    (
        "Q53 - Profit percentage by category",
        """
        SELECT p.category,
               SUM(o.profit) AS total_profit,
               SUM(o.sales) AS total_sales,
               CASE WHEN SUM(o.sales) = 0 THEN 0 ELSE ROUND((SUM(o.profit) * 100.0) / SUM(o.sales), 2) END AS profit_percentage
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.category
        ORDER BY profit_percentage DESC
        """
    ),
    (
        "Q54 - Loss-making products",
        """
        SELECT p.product_id, p.product_name, SUM(o.profit) AS total_profit
        FROM products p
        JOIN orders o ON o.product_id = p.product_id
        GROUP BY p.product_id, p.product_name
        HAVING SUM(o.profit) < 0
        ORDER BY total_profit ASC
        """
    ),
    (
        "Q55 - Loss-making customers",
        """
        SELECT c.customer_id, c.customer_name, SUM(o.profit) AS total_profit
        FROM customers c
        JOIN orders o ON o.customer_id = c.customer_id
        GROUP BY c.customer_id, c.customer_name
        HAVING SUM(o.profit) < 0
        ORDER BY total_profit ASC
        """
    ),
]

advanced_analysis = [
    (
        "Q56 - Monthly sales trend",
        """
        SELECT strftime('%Y-%m', order_date) AS sales_month,
               SUM(sales) AS monthly_sales
        FROM orders
        GROUP BY strftime('%Y-%m', order_date)
        ORDER BY sales_month
        """
    ),
    (
        "Q57 - Yearly sales trend",
        """
        SELECT strftime('%Y', order_date) AS sales_year,
               SUM(sales) AS yearly_sales
        FROM orders
        GROUP BY strftime('%Y', order_date)
        ORDER BY sales_year
        """
    ),
    (
        "Q58 - Monthly profit trend",
        """
        SELECT strftime('%Y-%m', order_date) AS profit_month,
               SUM(profit) AS monthly_profit
        FROM orders
        GROUP BY strftime('%Y-%m', order_date)
        ORDER BY profit_month
        """
    ),
    (
        "Q59 - Best sales month",
        """
        WITH monthly_sales AS (
            SELECT strftime('%Y-%m', order_date) AS month_start, SUM(sales) AS total_sales
            FROM orders
            GROUP BY strftime('%Y-%m', order_date)
        )
        SELECT month_start, total_sales
        FROM monthly_sales
        ORDER BY total_sales DESC
        LIMIT 1
        """
    ),
    (
        "Q60 - Worst sales month",
        """
        WITH monthly_sales AS (
            SELECT strftime('%Y-%m', order_date) AS month_start, SUM(sales) AS total_sales
            FROM orders
            GROUP BY strftime('%Y-%m', order_date)
        )
        SELECT month_start, total_sales
        FROM monthly_sales
        ORDER BY total_sales ASC
        LIMIT 1
        """
    ),
    (
        "Q61 - Average sales per month",
        """
        WITH monthly_sales AS (
            SELECT strftime('%Y-%m', order_date) AS month_start, SUM(sales) AS total_sales
            FROM orders
            GROUP BY strftime('%Y-%m', order_date)
        )
        SELECT AVG(total_sales) AS average_monthly_sales
        FROM monthly_sales
        """
    ),
    (
        "Q62 - Average profit per month",
        """
        WITH monthly_profit AS (
            SELECT strftime('%Y-%m', order_date) AS month_start, SUM(profit) AS total_profit
            FROM orders
            GROUP BY strftime('%Y-%m', order_date)
        )
        SELECT AVG(total_profit) AS average_monthly_profit
        FROM monthly_profit
        """
    ),
    (
        "Q63 - Running sales total",
        """
        SELECT order_date, row_id, sales,
               SUM(sales) OVER (ORDER BY order_date, row_id) AS running_sales_total
        FROM orders
        ORDER BY order_date, row_id
        """
    ),
    (
        "Q64 - Running profit total",
        """
        SELECT order_date, row_id, profit,
               SUM(profit) OVER (ORDER BY order_date, row_id) AS running_profit_total
        FROM orders
        ORDER BY order_date, row_id
        """
    ),
    (
        "Q65 - Top customer in every region",
        """
        WITH regional_customer_sales AS (
            SELECT c.region, c.customer_id, c.customer_name, SUM(o.sales) AS total_sales
            FROM orders o
            JOIN customers c ON c.customer_id = o.customer_id
            GROUP BY c.region, c.customer_id, c.customer_name
        ), ranked AS (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY region ORDER BY total_sales DESC) AS rn
            FROM regional_customer_sales
        )
        SELECT region, customer_name, total_sales
        FROM ranked
        WHERE rn = 1
        ORDER BY region
        """
    ),
    (
        "Q66 - Top product in every category",
        """
        WITH category_product_sales AS (
            SELECT p.category, p.product_id, p.product_name, SUM(o.sales) AS total_sales
            FROM orders o
            JOIN products p ON p.product_id = o.product_id
            GROUP BY p.category, p.product_id, p.product_name
        ), ranked AS (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY total_sales DESC) AS rn
            FROM category_product_sales
        )
        SELECT category, product_name, total_sales
        FROM ranked
        WHERE rn = 1
        ORDER BY category
        """
    ),
    (
        "Q67 - Top city in every state",
        """
        WITH state_city_sales AS (
            SELECT c.state, c.city, SUM(o.sales) AS total_sales
            FROM orders o
            JOIN customers c ON c.customer_id = o.customer_id
            GROUP BY c.state, c.city
        ), ranked AS (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY state ORDER BY total_sales DESC) AS rn
            FROM state_city_sales
        )
        SELECT state, city, total_sales
        FROM ranked
        WHERE rn = 1
        ORDER BY state
        """
    ),
    (
        "Q68 - Highest order value in every category",
        """
        WITH category_order_values AS (
            SELECT p.category, o.order_id, o.sales
            FROM orders o
            JOIN products p ON p.product_id = o.product_id
        ), ranked AS (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY sales DESC, order_id) AS rn
            FROM category_order_values
        )
        SELECT category, order_id, sales
        FROM ranked
        WHERE rn = 1
        ORDER BY category
        """
    ),
    (
        "Q69 - Highest profit order in every region",
        """
        WITH region_order_profit AS (
            SELECT c.region, o.order_id, o.profit
            FROM orders o
            JOIN customers c ON c.customer_id = o.customer_id
        ), ranked AS (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY region ORDER BY profit DESC, order_id) AS rn
            FROM region_order_profit
        )
        SELECT region, order_id, profit
        FROM ranked
        WHERE rn = 1
        ORDER BY region
        """
    ),
    (
        "Q70 - Customer contribution percentage to total sales",
        """
        WITH customer_sales AS (
            SELECT customer_id, SUM(sales) AS total_sales
            FROM orders
            GROUP BY customer_id
        ), total_sales AS (
            SELECT SUM(total_sales) AS grand_total_sales
            FROM customer_sales
        )
        SELECT c.customer_id, c.customer_name, cs.total_sales,
               ROUND((cs.total_sales * 100.0) / t.grand_total_sales, 2) AS contribution_percentage
        FROM customer_sales cs
        JOIN customers c ON c.customer_id = cs.customer_id
        CROSS JOIN total_sales t
        ORDER BY contribution_percentage DESC
        """
    ),
]

for group in [customer_analysis, product_analysis, regional_analysis, profit_analysis, advanced_analysis]:
    for label, sql in group:
        business_results[label] = run_query(label, sql)

# Keep a few commonly inspected results in named variables
customer_top_5 = business_results["Q21 - Top 5 customers"]
region_top_10_cities = business_results["Q47 - Top 10 cities by sales"]
monthly_sales_trend = business_results["Q56 - Monthly sales trend"]

============================================================
Q21 - Top 5 customers
============================================================

   customer_name  total_sales
0    Sean Miller    25043.050
1   Tamara Chand    19052.218
2   Raymond Buch    15117.339
3   Tom Ashbrook    14595.620
4  Adrian Barton    14473.571

============================================================
Q22 - Bottom 5 customers
============================================================

     customer_name  total_sales
0    Thais Sissman        4.833
1     Lela Donovan        5.304
2     Carl Jackson       16.520
3  Mitch Gastineau       16.739
4       Roy Skaria       22.328

============================================================
Q23 - Customers who placed only one order
============================================================

   customer_id      customer_name  order_count
0     AR-10570     Anemone Ratner            1
1     AO-10810  Anthony O'Donnell            1
2     CJ-11875       Carl Jackson            1
3     JC-15385       Jenna Caffey            1
4     JR-15700     Jocasta Rupert            1
5     LD-16855       Lela Donovan            1
6     MG-18205    Mitch Gastineau            1
7     PH-18790  Patricia Hirasaki            1
8     RE-19405    Ricardo Emerson            1
9     RM-19750      Roland Murray            1
10    SM-20905  Susan MacKendrick            1
11    TC-21145      Theresa Coyne            1

============================================================
Q24 - Customers who placed more than 10 orders
============================================================

   customer_id         customer_name  order_count
0     EP-13915            Emily Phan           17
1     CK-12205   Chloris Kastensmidt           13
2     EA-14035         Erin Ashbrook           13
3     JE-15745            Joel Eaton           13
4     NS-18640          Noel Staavos           13
5     PG-18820       Patrick Gardner           13
6     SH-19975         Sally Hughsby           13
7     ZC-21910      Zuschuss Carroll           13
8     AH-10690         Anna Häberlin           12
9     BP-11095          Bart Pistole           12
10    BD-11320        Bill Donatelli           12
11    CC-12220          Chris Cortes           12
12    CS-12250       Chris Selesnick           12
13    CL-12565           Clay Ludtke           12
14    DK-12835       Damala Kotsonis           12
15    EH-13765          Edward Hooks           12
16    HG-14965         Henry Goldwyn           12
17    KD-16495         Keith Dawkins           12
18    KB-16585             Ken Black           12
19    KL-16645          Ken Lonsdale           12
20    LC-16885        Lena Creighton           12
21    PK-19075             Pete Kriz           12
22    RP-19390          Resi Pölking           12
23    RB-19465          Rick Bensley           12
24    SJ-20125         Sanjit Jacobs           12
25    SM-20950        Suzanne McNair           12
26    BF-11170            Ben Ferrer           11
27    BM-11650            Brian Moss           11
28    CS-11950        Carlos Soltero           11
29    CS-12355  Christine Sundaresam           11
30    CK-12595          Clytie Kelty           11
31    Dp-13240           Dean percer           11
32    GB-14530           George Bell           11
33    GT-14710             Greg Tran           11
34    GA-14725         Guy Armstrong           11
35    JG-15160          James Galang           11
36    JF-15490          Jeremy Farry           11
37    JL-15835              John Lee           11
38    JD-15895      Jonathan Doherty           11
39    LA-16780       Laura Armstrong           11
40    MA-17560          Matt Abelman           11
41    MM-17920         Michael Moore           11
42    MY-18295       Muhammed Yedwab           11
43    PO-18850       Patrick O'Brill           11
44    SZ-20035            Sam Zeldin           11
45    SE-20110          Sanjit Engle           11
46    SC-20725     Steven Cartwright           11
47    WB-21850         William Brown           11
48    XP-21865          Xylona Preis           11

============================================================
Q25 - Customers with above-average sales
============================================================

     customer_name  total_sales
0      Sean Miller    25043.050
1     Tamara Chand    19052.218
2     Raymond Buch    15117.339
3     Tom Ashbrook    14595.620
4    Adrian Barton    14473.571
..             ...          ...
289     Julie Kriz     2932.484
290    Shaun Weien     2921.544
291   Maris LaWare     2921.500
292       Rob Dowd     2912.894
293   Craig Yedwab     2900.026

[294 rows x 2 columns]

============================================================
Q26 - Customers generated highest profit
============================================================

  customer_name  total_profit
0  Tamara Chand     8981.3239

============================================================
Q27 - Customer purchased maximum quantity
============================================================

      customer_name  total_quantity
0  Jonathan Doherty             150

============================================================
Q28 - Customer with highest order value
============================================================

  customer_name        order_id     sales
0   Sean Miller  CA-2014-145317  22638.48

============================================================
Q29 - Customer with lowest order value
============================================================

      customer_name        order_id  sales
0  Zuschuss Carroll  US-2017-102288  0.444

============================================================
Q30 - Customers who never generated profit
============================================================

    customer_id    customer_name  total_profit
0      CS-12505    Cindy Stewart    -6626.3895
1      GT-14635   Grant Thornton    -4108.6589
2      LF-17185      Luke Foster    -3583.9770
3      SR-20425   Sharelle Roach    -3333.9144
4      HG-14965    Henry Goldwyn    -2797.9635
..          ...              ...           ...
150    TS-21085    Thais Sissman       -3.3156
151    AH-10120      Adrian Hane       -2.3146
152    MG-18205  Mitch Gastineau       -1.2453
153    PL-18925       Paul Lucas       -0.7527
154    JC-15340  Jasper Cacioppo       -0.3556

[155 rows x 3 columns]

============================================================
Q31 - Top 5 products by sales
============================================================

,product_id,product_name,total_sales
0,TEC-CO-10004722,Canon imageCLASS 2200 Advanced Copier,61599.824
1,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384
2,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,22638.480
3,FUR-CH-10002024,HON 5400 Series Task Chairs for Big and Tall,21870.576
4,OFF-BI-10001359,GBC DocuBind TL300 Electric Binding System,19823.479

============================================================
Q32 - Bottom 5 products by sales
============================================================

,product_id,product_name,total_sales
0,OFF-AP-10002203,Eureka Disposable Bags for Sanitaire Vibra Gro...,1.624
1,OFF-LA-10003388,Avery 5,5.760
2,OFF-PA-10000048,Xerox 20,6.480
3,OFF-EN-10001535,Grip Seal Envelopes,7.072
4,OFF-AR-10003986,Avery Hi-Liter Pen Style Six-Color Fluorescent...,7.700

============================================================
Q33 - Top 5 products by profit
============================================================

,product_id,product_name,total_profit
0,TEC-CO-10004722,Canon imageCLASS 2200 Advanced Copier,25199.9280
1,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,7753.0390
2,TEC-CO-10001449,Hewlett Packard LaserJet 3310 Copier,6983.8836
3,TEC-CO-10003763,Canon PC1060 Personal Laser Copier,4570.9347
4,TEC-AC-10002049,Logitech G19 Programmable Gaming Keyboard,4425.3432

============================================================
Q34 - Most sold product
============================================================

        product_id                        product_name  total_quantity
0  TEC-AC-10003832  Logitech P710e Mobile Speakerphone              75

============================================================
Q35 - Least sold product
============================================================

,product_id,product_name,total_quantity
0,FUR-BO-10002206,"Bush Saratoga Collection 5-Shelf Bookcase, Han...",1

============================================================
Q36 - Highest revenue generating category
============================================================

     category  total_sales
0  Technology   836154.033

============================================================
Q37 - Lowest revenue generating category
============================================================

          category  total_sales
0  Office Supplies   719047.032

============================================================
Q38 - Highest profit generating sub-category
============================================================

  sub_category  total_profit
0      Copiers    55617.8249

============================================================
Q39 - Lowest profit generating sub-category
============================================================

  sub_category  total_profit
0       Tables   -17725.4811

============================================================
Q40 - Products with above-average sales
============================================================

,product_id,product_name,total_sales
0,TEC-CO-10004722,Canon imageCLASS 2200 Advanced Copier,61599.824
1,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384
2,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,22638.480
3,FUR-CH-10002024,HON 5400 Series Task Chairs for Big and Tall,21870.576
4,OFF-BI-10001359,GBC DocuBind TL300 Electric Binding System,19823.479
...,...,...,...
442,TEC-PH-10001809,Panasonic KX T7736-B Digital phone,1259.580
443,TEC-AC-10001539,Logitech G430 Surround Sound Gaming Headset wi...,1247.844
444,OFF-AP-10000026,Tripp Lite Isotel 6 Outlet Surge Protector wit...,1243.788
445,FUR-CH-10003846,Hon Valutask Swivel Chairs,1242.054
446,OFF-ST-10001837,"SAFCO Mobile Desk Side File, Wire Frame",1240.040

============================================================
Q41 - Top performing region
============================================================

  region  total_sales
0   West  764634.4453

============================================================
Q42 - Lowest performing region
============================================================

  region  total_sales
0  South  402031.9833

============================================================
Q43 - Region with highest profit
============================================================

  region  total_profit
0   West    98008.2249

============================================================
Q44 - Region with highest quantity sold
============================================================

  region  total_quantity
0   West           12272

============================================================
Q45 - State with highest sales
============================================================

        state  total_sales
0  California  451036.5823

============================================================
Q46 - State with highest profit
============================================================

        state  total_profit
0  California    59398.3125

============================================================
Q47 - Top 10 cities by sales
============================================================

            city  total_sales
0  New York City  210926.9921
1    Los Angeles  141770.8106
2   Philadelphia  130921.1550
3        Seattle  108638.2118
4  San Francisco  107084.0535
5        Houston   87156.5178
6        Chicago   61351.2940
7      San Diego   39816.4470
8       Columbus   39808.7310
9         Monroe   35707.0400

============================================================
Q48 - Top 10 cities by profit
============================================================

            city  total_profit
0  New York City    41892.8872
1        Seattle    19979.9074
2  San Francisco    17141.7985
3        Houston    13279.5153
4   Philadelphia    12376.6486
5    Los Angeles    11113.7756
6         Auburn     8069.6656
7      San Diego     7572.9627
8        Concord     7078.7017
9        Chicago     5433.3343

============================================================
Q49 - Total company profit
============================================================

   total_company_profit
0           286397.0217

============================================================
Q50 - Average profit per order
============================================================

   average_profit_per_order
0                 28.656896

============================================================
Q51 - Most profitable order
============================================================

         order_id  row_id     sales    profit
0  CA-2016-118689    6827  17499.95  8399.976

============================================================
Q52 - Least profitable order
============================================================

         order_id  row_id     sales    profit
0  CA-2016-108196    7773  4499.985 -6599.978

============================================================
Q53 - Profit percentage by category
============================================================

          category  total_profit  total_sales  profit_percentage
0       Technology   145454.9481  836154.0330              17.40
1  Office Supplies   122490.8008  719047.0320              17.04
2        Furniture    18451.2728  741999.7953               2.49

============================================================
Q54 - Loss-making products
============================================================

,product_id,product_name,total_profit
0,TEC-MA-10000418,Cubify CubeX 3D Printer Double Head Print,-8.879970e+03
1,TEC-MA-10000822,Lexmark MX611dhe Monochrome Laser Printer,-4.589973e+03
2,TEC-MA-10004125,Cubify CubeX 3D Printer Triple Head Print,-3.839990e+03
3,FUR-TA-10000198,Chromcraft Bull-Nose Wood Oval Conference Tabl...,-2.876116e+03
4,FUR-TA-10001889,Bush Advantage Collection Racetrack Conference...,-1.934398e+03
...,...,...,...
297,OFF-FA-10004968,Rubber Band Ball,-2.992000e-01
298,OFF-BI-10001132,"Acco PRESSTEX Data Binder with Storage Hooks, ...",-1.614000e-01
299,FUR-CH-10004289,Global Super Steno Chair,-4.440892e-15
300,OFF-BI-10002931,"Avery Trapezoid Extra Heavy Duty 4"" Binders",-3.552714e-15
301,OFF-SU-10003505,Premier Electric Letter Opener,-3.552714e-15

============================================================
Q55 - Loss-making customers
============================================================

    customer_id    customer_name  total_profit
0      CS-12505    Cindy Stewart    -6626.3895
1      GT-14635   Grant Thornton    -4108.6589
2      LF-17185      Luke Foster    -3583.9770
3      SR-20425   Sharelle Roach    -3333.9144
4      HG-14965    Henry Goldwyn    -2797.9635
..          ...              ...           ...
150    TS-21085    Thais Sissman       -3.3156
151    AH-10120      Adrian Hane       -2.3146
152    MG-18205  Mitch Gastineau       -1.2453
153    PL-18925       Paul Lucas       -0.7527
154    JC-15340  Jasper Cacioppo       -0.3556

[155 rows x 3 columns]

============================================================
Q56 - Monthly sales trend
============================================================

   sales_month  monthly_sales
0      2014-01     14236.8950
1      2014-02      4519.8920
2      2014-03     55691.0090
3      2014-04     28295.3450
4      2014-05     23648.2870
5      2014-06     34595.1276
6      2014-07     33946.3930
7      2014-08     27909.4685
8      2014-09     81777.3508
9      2014-10     31453.3930
10     2014-11     78628.7167
11     2014-12     69545.6205
12     2015-01     18174.0756
13     2015-02     11951.4110
14     2015-03     38726.2520
15     2015-04     34195.2085
16     2015-05     30131.6865
17     2015-06     24797.2920
18     2015-07     28765.3250
19     2015-08     36898.3322
20     2015-09     64595.9180
21     2015-10     31404.9235
22     2015-11     75972.5635
23     2015-12     74919.5212
24     2016-01     18542.4910
25     2016-02     22978.8150
26     2016-03     51715.8750
27     2016-04     38750.0390
28     2016-05     56987.7280
29     2016-06     40344.5340
30     2016-07     39261.9630
31     2016-08     31115.3743
32     2016-09     73410.0249
33     2016-10     59687.7450
34     2016-11     79411.9658
35     2016-12     96999.0430
36     2017-01     43971.3740
37     2017-02     20301.1334
38     2017-03     58872.3528
39     2017-04     36521.5361
40     2017-05     44261.1102
41     2017-06     52981.7257
42     2017-07     45264.4160
43     2017-08     63120.8880
44     2017-09     87866.6520
45     2017-10     77776.9232
46     2017-11    118447.8250
47     2017-12     83829.3188

============================================================
Q57 - Yearly sales trend
============================================================

  sales_year  yearly_sales
0       2014   484247.4981
1       2015   470532.5090
2       2016   609205.5980
3       2017   733215.2552

============================================================
Q58 - Monthly profit trend
============================================================

   profit_month  monthly_profit
0       2014-01       2450.1907
1       2014-02        862.3084
2       2014-03        498.7299
3       2014-04       3488.8352
4       2014-05       2738.7096
5       2014-06       4976.5244
6       2014-07       -841.4826
7       2014-08       5318.1050
8       2014-09       8328.0994
9       2014-10       3448.2573
10      2014-11       9292.1269
11      2014-12       8983.5699
12      2015-01      -3281.0070
13      2015-02       2813.8508
14      2015-03       9732.0978
15      2015-04       4187.4962
16      2015-05       4667.8690
17      2015-06       3335.5572
18      2015-07       3288.6483
19      2015-08       5355.8084
20      2015-09       8209.1627
21      2015-10       2817.3660
22      2015-11      12474.7884
23      2015-12       8016.9659
24      2016-01       2824.8233
25      2016-02       5004.5795
26      2016-03       3611.9680
27      2016-04       2977.8149
28      2016-05       8662.1464
29      2016-06       4750.3781
30      2016-07       4432.8779
31      2016-08       2062.0693
32      2016-09       9328.6576
33      2016-10      16243.1425
34      2016-11       4011.4075
35      2016-12      17885.3093
36      2017-01       7140.4391
37      2017-02       1613.8720
38      2017-03      14751.8915
39      2017-04        933.2900
40      2017-05       6342.5828
41      2017-06       8223.3357
42      2017-07       6952.6212
43      2017-08       9040.9557
44      2017-09      10991.5556
45      2017-10       9275.2755
46      2017-11       9690.1037
47      2017-12       8483.3468

============================================================
Q59 - Best sales month
============================================================

  month_start  total_sales
0     2017-11   118447.825

============================================================
Q60 - Worst sales month
============================================================

  month_start  total_sales
0     2014-02     4519.892

============================================================
Q61 - Average sales per month
============================================================

   average_monthly_sales
0           47858.351256

============================================================
Q62 - Average profit per month
============================================================

   average_monthly_profit
0             5966.604619

============================================================
Q63 - Running sales total
============================================================

      order_date  row_id    sales  running_sales_total
0     2014-01-03    7981   16.448         1.644800e+01
1     2014-01-04     740   11.784         2.823200e+01
2     2014-01-04     741  272.736         3.009680e+02
3     2014-01-04     742    3.540         3.045080e+02
4     2014-01-05    1760   19.536         3.240440e+02
...          ...     ...      ...                  ...
9989  2017-12-30     908   90.930         2.297110e+06
9990  2017-12-30     909   52.776         2.297163e+06
9991  2017-12-30    1297   13.904         2.297177e+06
9992  2017-12-30    1298   20.720         2.297198e+06
9993  2017-12-30    5092    3.024         2.297201e+06

[9994 rows x 4 columns]

============================================================
Q64 - Running profit total
============================================================

      order_date  row_id   profit  running_profit_total
0     2014-01-03    7981   5.5512                5.5512
1     2014-01-04     740   4.2717                9.8229
2     2014-01-04     741 -64.7748              -54.9519
3     2014-01-04     742  -5.4870              -60.4389
4     2014-01-05    1760   4.8840              -55.5549
...          ...     ...      ...                   ...
9989  2017-12-30     908   2.7279           286366.8417
9990  2017-12-30     909  19.7910           286386.6327
9991  2017-12-30    1297   4.5188           286391.1515
9992  2017-12-30    1298   6.4750           286397.6265
9993  2017-12-30    5092  -0.6048           286397.0217

[9994 rows x 4 columns]

============================================================
Q65 - Top customer in every region
============================================================

    region customer_name  total_sales
0  Central  Ken Lonsdale    14175.229
1     East  Raymond Buch    15117.339
2    South   Sean Miller    25043.050
3     West  Tamara Chand    19052.218

============================================================
Q66 - Top product in every category
============================================================

,category,product_name,total_sales
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.576
1,Office Supplies,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384
2,Technology,Canon imageCLASS 2200 Advanced Copier,61599.824

============================================================
Q67 - Top city in every state
============================================================

                   state           city  total_sales
0                Alabama     Montgomery    6234.9100
1                Arizona        Phoenix   26920.0750
2               Arkansas   Fayetteville    4582.5560
3             California    Los Angeles  141770.8106
4               Colorado         Aurora   12645.8032
5            Connecticut        Norwich   11285.8660
6               Delaware          Dover   14135.1620
7   District of Columbia     Washington    2198.4500
8                Florida   Jacksonville   11404.0978
9                Georgia       Columbus   21731.4200
10              Illinois        Chicago   61351.2940
11               Indiana       La Porte    9881.3820
12                  Iowa      Urbandale   10880.5460
13                Kansas         Olathe    1727.6520
14              Kentucky       Richmond   10045.1180
15             Louisiana         Monroe   10360.0420
16              Maryland        Clinton    1191.5800
17         Massachusetts       Lawrence   10782.4290
18              Michigan        Detroit   19905.0138
19             Minnesota    Minneapolis   21488.9005
20           Mississippi        Jackson   16690.5540
21              Missouri    Saint Louis    3458.2400
22              Nebraska          Omaha    3747.6680
23                Nevada      Las Vegas     993.9020
24         New Hampshire        Concord    6410.9960
25            New Jersey     Hackensack    5371.0900
26            New Mexico       Carlsbad    3133.9240
27              New York  New York City  210926.9921
28        North Carolina         Monroe   25346.9980
29                  Ohio       Columbus   10672.2670
30              Oklahoma         Edmond    3908.4020
31                Oregon          Salem    8025.7070
32          Pennsylvania   Philadelphia  130921.1550
33          Rhode Island     Providence   10475.4420
34          South Dakota    Sioux Falls    2339.5980
35             Tennessee       Columbia   11101.5090
36                 Texas        Houston   87156.5178
37                  Utah         Murray    7198.7610
38              Virginia    Springfield   13344.7020
39            Washington        Seattle  108638.2118
40             Wisconsin      Milwaukee   15873.4280

============================================================
Q68 - Highest order value in every category
============================================================

          category        order_id      sales
0        Furniture  CA-2017-118892   4416.174
1  Office Supplies  CA-2016-117121   9892.740
2       Technology  CA-2014-145317  22638.480

============================================================
Q69 - Highest profit order in every region
============================================================

    region        order_id     profit
0  Central  CA-2017-166709  5039.9856
1     East  CA-2017-140151  6719.9808
2    South  CA-2015-145352  3177.4750
3     West  CA-2016-118689  8399.9760

============================================================
Q70 - Customer contribution percentage to total sales
============================================================

    customer_id    customer_name  total_sales  contribution_percentage
0      SM-20320      Sean Miller    25043.050                     1.09
1      TC-20980     Tamara Chand    19052.218                     0.83
2      RB-19360     Raymond Buch    15117.339                     0.66
3      TA-21385     Tom Ashbrook    14595.620                     0.64
4      AB-10105    Adrian Barton    14473.571                     0.63
..          ...              ...          ...                      ...
788    RE-19405  Ricardo Emerson       48.360                     0.00
789    RM-19750    Roland Murray       98.350                     0.00
790    RS-19870       Roy Skaria       22.328                     0.00
791    SG-20890   Susan Gilcrest       47.946                     0.00
792    TS-21085    Thais Sissman        4.833                     0.00

[793 rows x 4 columns]

## Final Ranked Customer Report

This last cell produces the combined report with customer name, total sales, and rank.

In [17]:
final_report = run_query(
    "Final Report - Customer Name, Total Sales, Rank",
    """
    WITH customer_totals AS (
        SELECT customer_id, SUM(sales) AS total_sales
        FROM orders
        GROUP BY customer_id
    )
    SELECT c.customer_name AS "Customer Name",
           ct.total_sales AS "Total Sales",
           RANK() OVER (ORDER BY ct.total_sales DESC) AS "Rank"
    FROM customer_totals ct
    JOIN customers c ON c.customer_id = ct.customer_id
    ORDER BY 3, 1
    """
)

final_report

============================================================
Final Report - Customer Name, Total Sales, Rank
============================================================

       Customer Name  Total Sales  Rank
0        Sean Miller    25043.050     1
1       Tamara Chand    19052.218     2
2       Raymond Buch    15117.339     3
3       Tom Ashbrook    14595.620     4
4      Adrian Barton    14473.571     5
..               ...          ...   ...
788       Roy Skaria       22.328   789
789  Mitch Gastineau       16.739   790
790     Carl Jackson       16.520   791
791     Lela Donovan        5.304   792
792    Thais Sissman        4.833   793

[793 rows x 3 columns]

       Customer Name  Total Sales  Rank
0        Sean Miller    25043.050     1
1       Tamara Chand    19052.218     2
2       Raymond Buch    15117.339     3
3       Tom Ashbrook    14595.620     4
4      Adrian Barton    14473.571     5
..               ...          ...   ...
788       Roy Skaria       22.328   789
789  Mitch Gastineau       16.739   790
790     Carl Jackson       16.520   791
791     Lela Donovan        5.304   792
792    Thais Sissman        4.833   793

[793 rows x 3 columns]